In [3]:
# operasi penjumlahan vektor
# menggunakan list

a = [1, 2, 3]
b = [5, 1, 2]

c = [0, 0, 0]
for i in range(len(a)):
    c[i] = a[i] + b[i]

In [4]:
c

[6, 3, 5]

In [5]:
a = [1, 2, 3]
b = [5, 1, 2]

def jumlah(a, b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

In [6]:
# tipe data dari numpy -> np.array
import numpy as np

a = [1,2,3,4]
b = [6,4,2,7]
np_a = np.array(a)
np_b = np.array(b)

In [9]:
a + b

[1, 2, 3, 4, 6, 4, 2, 7]

In [10]:
np_a + np_b

array([ 7,  6,  5, 11])

In [11]:
# cek performa
a = [1,2,3,4,5,6,7,8,9,10]
b = [1,1,1,1,1,1,1,1,1,1]

In [12]:
%timeit jumlah(a,b)

2.35 µs ± 46.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
np_a = np.array(a)
np_b = np.array(b)

%timeit np_a + np_b

940 ns ± 8.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [15]:
# contoh array

a1d = [1,2,3,4,5]
a1d = np.array(a1d)
a1d

array([1, 2, 3, 4, 5])

In [16]:
a2d = [[1,2],[5,4],[7,8]]
a2d = np.array(a2d)
a2d

array([[1, 2],
       [5, 4],
       [7, 8]])

In [17]:
a2d = [[1,2],[5,4,5],[7,8]]
a2d = np.array(a2d)
a2d

C:\Users\user\AppData\Local\Temp\ipykernel_6060\3074863642.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2d = np.array(a2d)


array([list([1, 2]), list([5, 4, 5]), list([7, 8])], dtype=object)

In [18]:
A = [[1,2],[5,4],[7,8]]
A = np.array(A)
A

array([[1, 2],
       [5, 4],
       [7, 8]])

In [19]:
A[2][1]

8

In [20]:
A[2,1]

8

In [21]:
# memanggil baris
A[1]

array([5, 4])

In [22]:
A[1, :]

array([5, 4])

In [23]:
# memanggil kolom
A[:, 0]

array([1, 5, 7])

In [25]:
# special array
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.arange(1,6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [37]:
np.empty(10)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [36]:
np.linspace(1, 10, 100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [38]:
A.ndim

2

In [39]:
A.shape

(3, 2)

In [40]:
A.size

6

In [42]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [43]:
a.reshape((4,2))

array([[2, 3],
       [1, 6],
       [5, 7],
       [5, 6]])

In [44]:
a.reshape((4,2)).T

array([[2, 1, 5, 5],
       [3, 6, 7, 6]])

In [45]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [46]:
a[np.newaxis]

array([[2, 3, 1, 6, 5, 7, 5, 6]])

In [47]:
a[np.newaxis].shape

(1, 8)

In [48]:
a[:,np.newaxis]

array([[2],
       [3],
       [1],
       [6],
       [5],
       [7],
       [5],
       [6]])

In [49]:
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [51]:
np.expand_dims(a, axis=1).shape

(8, 1)

Querying

In [52]:
mat = [[5,4,3,8,2], [4,6,3,7,4], [1,6,4,5,6]]
mat = np.array(mat)
mat

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6]])

In [55]:
mat[1:2, -2:]

array([[7, 4]])

In [56]:
mat > 4

array([[ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True, False,  True,  True]])

In [57]:
mat[mat > 4]

array([5, 8, 6, 7, 6, 5, 6])

In [61]:
mahasiswa = np.array(['Taehyung', 'Jungkook', 'jimin', 'jin'])
nilai = np.array([80, 50, 90, 55])

In [62]:
nilai < 60

array([False,  True, False,  True])

In [65]:
mahasiswa[nilai < 60]

array(['Jungkook', 'jin'], dtype='<U8')

In [76]:
A = np.array([[1,2], [3,4]])
B = np.array([[6,5], [2,7]])
C = np.array([1,2])

In [77]:
A*B

array([[ 6, 10],
       [ 6, 28]])

In [69]:
A

array([[1, 2],
       [3, 4]])

In [70]:
B

array([[6, 5],
       [2, 7]])

In [71]:
# PERKALIAN MATRIKS SECARA ALJABAR LINIER
A @ B

array([[10, 19],
       [26, 43]])

In [75]:
A.mean(axis=1)

array([1.5, 3.5])

In [78]:
np.random.random((2,3))

array([[0.71350651, 0.01050727, 0.24256574],
       [0.36451852, 0.01993047, 0.69805526]])